# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('show', '0002_delete_t_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader_emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('T_username', models.CharField(default='匿名', max_length=20, verbose_name='用户姓名')),
                ('T_email_post_time', models.TimeField(null=True, verbose_name='邮箱记录创建时间')),
            ],
        ),
    ]
