# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('show', '0003_reader_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_reader_emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('username', models.CharField(default='匿名', max_length=20, verbose_name='用户姓名')),
                ('email_post_time', models.TimeField(null=True, verbose_name='邮箱记录创建时间')),
            ],
        ),
        migrations.DeleteModel(
            name='reader_emails',
        ),
    ]
