# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('show', '0004_auto_20190207_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_reader_emails',
            name='email_post_time',
            field=models.TextField(max_length=20, null=True, verbose_name='邮箱记录创建时间'),
        ),
    ]
