# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_article_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.IntegerField(null=True, verbose_name='关联文章的id')),
                ('filename', models.CharField(max_length=20, null=True, verbose_name='图片名称')),
                ('img', models.FileField(upload_to='article/image/')),
                ('upload_time', models.TimeField(auto_now=True, verbose_name='上传时间')),
            ],
        ),
        migrations.CreateModel(
            name='T_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(verbose_name='标题id')),
                ('content', models.TextField(max_length=50000, verbose_name='html文本内容')),
                ('markdown_text', models.TextField(max_length=50000, null=True, verbose_name='md文本')),
            ],
        ),
    ]
