# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backstage', '0002_auto_20190210_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_day_visit_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.TimeField(verbose_name='访问时间')),
                ('visit_num', models.IntegerField(verbose_name='访问数量')),
            ],
        ),
        migrations.CreateModel(
            name='T_everyday_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='访问日期')),
                ('visit_num', models.IntegerField(verbose_name='访问量')),
            ],
        ),
        migrations.CreateModel(
            name='T_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章类型')),
                ('type', models.CharField(max_length=20, verbose_name='类型名称')),
                ('type_id', models.IntegerField(verbose_name='类型id')),
            ],
        ),
        migrations.AddField(
            model_name='t_title',
            name='description',
            field=models.TextField(null=True, verbose_name='内容简述'),
        ),
        migrations.AddField(
            model_name='t_title',
            name='img',
            field=models.FileField(default='article/image/default.jpg', upload_to='article/image/'),
        ),
        migrations.AlterField(
            model_name='t_title',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='t_title',
            name='time',
            field=models.CharField(max_length=20, verbose_name='录入时间'),
        ),
        migrations.AlterField(
            model_name='t_title',
            name='title',
            field=models.TextField(verbose_name='标题'),
        ),
    ]
