# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backstage', '0003_auto_20190210_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_title',
            name='show',
            field=models.CharField(default=1, max_length=1, null=True, verbose_name='是否展示'),
        ),
    ]
